version: "3"

services:
  app:
    build: .
    command: poetry run python todo/manage.py runserver 0.0.0.0:8000
    volumes:
      - .dockerenv:/.venv
      - .:/todo
    ports:
      - "8000:8000"
    depends_on:
      - db
  db:
    image: postgres:15
    restart: always
    platform: linux/x86_64  # M1 Macの場合必要
    environment:
      POSTGRES_DB: django_db
      POSTGRES_PASSWORD: password
      POSTGRES_USER: user
      TZ: 'Asia/Tokyo'
    volumes:
      - postgres_data:/var/lib/postgresql
    ports:
      - 5432:5432
volumes:
  postgres_data:
